<?php

$tid = $this->tournament->need('tid');

$backUrl = $this->url('backend/tournament/edit', ['tid' => $tid]);

$this->setup(array(
    'title' => 'Delete this tournament',
    'panel' => 'centered-panel',
    'back' => array(
        'Tournament' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this tournament? This also removes both categories and all their participants, groups and matches.') ?></span></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/tournament/delete', ['tid' => $tid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this tournament') ?></span>
        </a>

        &nbsp;

        <a href="<?= $backUrl ?>" class="default-button"><?= $this->t('No, go back') ?></a>
    </p>
</div>
