<?php

$this->setup(array(
    'title' => 'Tournament-Administration',
    'panel' => 'centered-panel large-sized',
    'back' => true,
    'links' => array(
        'User-Administration' => $this->url('backend/user'),
        'Booking-Administration' => $this->url('backend/booking'),
        'Configuration' => $this->url('backend/config'),
    ),
));

?>

<div>
    <h1><?= $this->t('Tournament-Administration') ?></h1>

    <div class="separator-small"></div>

    <p><?= $this->t('Here you can create, edit or delete tournaments.') ?></p>

    <div class="separator separator-line"></div>

    <p><a href="<?= $this->url('backend/tournament/edit') ?>" class="unlined gray"><span class="symbolic symbolic-plus"><?= $this->t('New tournament') ?></span></a></p>

    <div class="separator separator-line"></div>

    <?php if ($this->tournaments): ?>

        <div class="table-scroll">
            <table class="default-table">
                <tr>
                    <th><?= $this->t('Name') ?></th>
                    <th><?= $this->t('Date (Start)') ?></th>
                    <th><?= $this->t('Date (End)') ?></th>
                    <th><?= $this->t('Status') ?></th>
                    <th></th>
                </tr>

                <?php foreach ($this->tournaments as $tournament): ?>
                    <tr>
                        <td><?= $this->escapeHtml($tournament->getMeta('name', '-')) ?></td>
                        <td><?= $this->dateFormat(new \DateTime($tournament->need('date_start')), \IntlDateFormatter::MEDIUM) ?></td>
                        <td><?= $this->dateFormat(new \DateTime($tournament->need('date_end')), \IntlDateFormatter::MEDIUM) ?></td>
                        <td><?= $this->t($tournament->getStatus()) ?></td>
                        <td><a href="<?= $this->url('backend/tournament/edit', ['tid' => $tournament->need('tid')]) ?>"><?= $this->t('Edit') ?></a></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

    <?php else: ?>

        <p><?= $this->t('No tournaments have been created yet.') ?></p>

    <?php endif; ?>

</div>
