<?php

$this->setup(array(
    'title' => 'Tournaments',
    'panel' => 'centered-panel large-sized',
    'back' => true,
));

?>

<div>
    <h1><?= $this->t('Tournaments') ?></h1>

    <div class="separator-small"></div>

    <?php if ($this->tournaments): ?>

        <table class="default-table">
            <tr>
                <th><?= $this->t('Name') ?></th>
                <th><?= $this->t('Date (Start)') ?></th>
                <th><?= $this->t('Date (End)') ?></th>
                <th><?= $this->t('Status') ?></th>
                <th></th>
            </tr>

            <?php foreach ($this->tournaments as $tournament): ?>
                <tr>
                    <td><?= $this->escapeHtml($tournament->getMeta('name', '-')) ?></td>
                    <td><?= $this->dateFormat(new \DateTime($tournament->need('date_start')), \IntlDateFormatter::MEDIUM) ?></td>
                    <td><?= $this->dateFormat(new \DateTime($tournament->need('date_end')), \IntlDateFormatter::MEDIUM) ?></td>
                    <td><?= $this->t($tournament->getStatus()) ?></td>
                    <td><a href="<?= $this->url('tournament/view', ['tid' => $tournament->need('tid')]) ?>"><?= $this->t('View') ?></a></td>
                </tr>
            <?php endforeach; ?>
        </table>

    <?php else: ?>

        <p><?= $this->t('There are no tournaments at the moment.') ?></p>

    <?php endif; ?>

</div>
